language: java

jdk:
- oraclejdk8
sudo: false
# cache the build tool's caches
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    token: SONAR_TOKEN
install:
- mvn dependency:go-offline
#script:
#  #  - mvn clean package
#  - mvn install -DskipTests=true
script:
  - sonar-scanner
  - mvn verify site sonar:sonar -Dmaven.test.failure.ignore=true
   
