language: java

jdk:
- oraclejdk8
sudo: false
# cache the build tool's caches
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    token:
      secure: $SONAR_TOKEN
install: true
#- mvn dependency:go-offline
#script:
#  #  - mvn clean package
#  - mvn install -DskipTests=true
script:
   - sonar-scanner
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
   
