language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "xylene1980-github"
    token:
      secure: "$SONAR_TOKEN"
branches:
  except:
  - /^tr\..*/
  only:
  - master
jdk:
- oraclejdk8
script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
   
